[project]
name = "acs-nativity-timeseries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "censusdis>=1.4",
    "ipykernel>=7.2.0",
    "plotly>=6.5.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.2",
]
